### PR TITLE
Fix bugs for Required and Science command not being able to load JSON files.

### LINKED ISSUE #116: Fix bugs retrieving JSON files in JAR file.
Currently unable to load JSON module files when our app is converted into a JAR file.

### PR DESCRIPTION
**Pull request by yan-soon**
Follow up from SAM's previous PR about loading files with our JAR file.

**RequiredCommandStorage**
Added 2 methods to help with loading the files in our JAR file:

1. `getFileNameFromResource(String fileName)`

Takes the original fileName (eg. data/sciencemodules.json) and converts it into a readable path when using our JAR file.

2. `getModulesFromJsonFile(String filePath)`

Takes the converted readable path and loads the modules from the JSON file.

**RequiredCommand**

Minor changes to suit the changes with RequiredCommandStorage.

**ScienceCommand**

Now makes use of the methods in RequiredCommandStorage to retrieve the relevant Science Modules from the JSON file.
As such, it should now also work in our JAR file.

**RequiredCommandStorageTest** **RequiredCommandTest** **ScienceCommandTest**

Updated various variables and names to fit the changes in the above classes.

**Notes**
Test Coverage remains unchanged from previous PR.

### CODE REVIEW

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java [hunk 1]
```diff
@@ -16,6 +20,46 @@
...
     private ObservableList<Module> requiredInternship;
 
+    /**
+     * Makes use of classLoaders to convert the original file path
+     * into one that can be readable during runtime.
+     * @param fileName Original file path.
+     * @return Converted runtime path.
+     * @throws IOException When the provided fileName is invalid.
+     */
+    public String getFileNameFromResource(String fileName) throws IOException {
```
Comment (Silvernitro) [inline src/main/java/seedu/address/storage/RequiredCommandStorage.java]: Shall we make this `private`? This fxn should be uniquely called by this class only since it calls the inherited `Object.getClass()` method that depends on this class's runtime `Class`

Comment (Silvernitro) [reply src/main/java/seedu/address/storage/RequiredCommandStorage.java]: And actually this fxn gets the file content from a resource and returns it as a string right HAHA not the file name, as mentioned in the fxn name

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java [hunk 2]
```diff
@@ -16,6 +20,46 @@
...
+    }
+
+    /**
+     * Converts a given JSON file via its runtime path, into a list of Modules.
+     * @param filePath Converted runtime path.
+     * @return List of modules taken from the JSON file via the runtime path.
+     * @throws IOException When the filePath is invalid.
+     * @throws IllegalValueException When the data from the JSON file violates some constraints.
+     */
+    public ObservableList<Module> getModulesFromJsonFile(String filePath) throws IOException, IllegalValueException {
```
Comment (Silvernitro) [inline src/main/java/seedu/address/storage/RequiredCommandStorage.java]: This method is reading in a JSON string, like `"{ module: { title: "abc", mc: "2" } }"`, not a file path 😁

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java [hunk 3]
```diff
@@ -16,6 +20,46 @@
...
+            return dataString.toString();
+        }
+    }
+
+    /**
+     * Converts a given JSON file via its runtime path, into a list of Modules.
+     * @param filePath Converted runtime path.
+     * @return List of modules taken from the JSON file via the runtime path.
+     * @throws IOException When the filePath is invalid.
+     * @throws IllegalValueException When the data from the JSON file violates some constraints.
```
Comment (Silvernitro) [inline src/main/java/seedu/address/storage/RequiredCommandStorage.java]: Should we list out what the constraints are? I think most people won't know, including me HAHA

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java [hunk 4]
```diff
@@ -26,12 +70,11 @@
...
      * @throws IOException When path is invalid.
-     * @throws DataConversionException When there is an error converting from the JSON file.
+     * @throws IllegalValueException When the data from the JSON file violates some constraints.
      */
-    public void setRequiredFoundation(Path path) throws IOException, DataConversionException {
-        JsonGradPadStorage storage = new JsonGradPadStorage(path);
-        Optional<ReadOnlyGradPad> gradPad = storage.readGradPad();
-        requiredFoundation = gradPad.orElseThrow().getModuleList();
+    public void setRequiredFoundation(String path) throws IOException, IllegalValueException {
+        String fileName = getFileNameFromResource(path);
```
Comment (Silvernitro) [inline src/main/java/seedu/address/storage/RequiredCommandStorage.java]: As mentioned above, this is actually the entire content of the file stored as a string, not the file name 😁

File: src/main/java/seedu/address/storage/RequiredCommandMessages.java [hunk 5]
```diff
@@ -19,9 +16,14 @@
...
+    public static final String FOUNDATION_PATH = "data/foundationmodules.json";
+    public static final String INTERNSHIP_PATH = "data/industrialexperience.json";
+    public static final String ITPROF_PATH = "data/ITProfessionalism.json";
+    public static final String MATHANDSCI_PATH = "data/mathandsciencemodules.json";
+    public static final String SCIENCE_PATH = "data/sciencemodules.json";
+    public static final String TEST_FOUNDATION_PATH = "src/main/resources/data/foundationmodules.json";
+    public static final String TEST_INTERNSHIP_PATH = "src/main/resources/data/industrialexperience.json";
+    public static final String TEST_ITPROF_PATH = "src/main/resources/data/ITProfessionalism.json";
+    public static final String TEST_MATHANDSCI_PATH = "src/main/resources/data/mathandsciencemodules.json";
+    public static final String TEST_SCIENCE_PATH = "src/main/resources/data/sciencemodules.json";
```
Comment (Silvernitro) [inline src/main/java/seedu/address/storage/RequiredCommandMessages.java]: Should we store these constants in the test package instead? I think it might not be so nice to mix production code and test code 😁  None of the production classes need to reference these anyway hehe

**Review by Silvernitro — COMMENTED** [review]
Just a few comments! But overall nice fix 👍  it works smoothly now

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java (hunk 1 above)
Comment (yan-soon) [reply src/main/java/seedu/address/storage/RequiredCommandStorage.java]: Good point, I've made it private and changed the method and param names HAHAHA. I think I got the method mixed up.

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java (hunk 2 above)
Comment (yan-soon) [reply src/main/java/seedu/address/storage/RequiredCommandStorage.java]: Roger, changed as per above!

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java (hunk 3 above)
Comment (yan-soon) [reply src/main/java/seedu/address/storage/RequiredCommandStorage.java]: HAHAHA I initially took it straight from the intellij java docs, but I've listed the constaints explicitly now.

File: src/main/java/seedu/address/storage/RequiredCommandStorage.java (hunk 4 above)
Comment (yan-soon) [reply src/main/java/seedu/address/storage/RequiredCommandStorage.java]: Roger, changed as per above!

File: src/main/java/seedu/address/storage/RequiredCommandMessages.java (hunk 5 above)
Comment (yan-soon) [reply src/main/java/seedu/address/storage/RequiredCommandMessages.java]: Great point, I've shifted it to the `RequiredCommandStorageTest` class and the other test classes now import from there instead of the `RequiredCommandMessages` class.

**Review by shaokiat — COMMENTED** [review]
LGTM! 👍

**Review by shaokiat — APPROVED** [review]

**Review by Silvernitro — APPROVED** [review]
Nice one 🥇
