### PR TITLE
Add required modules to NUSMods + fix resource dependencies

### LINKED ISSUE #119: Fix NUSMods json dependencies + other minor tweaks
- Change `NUSMods` package such that it can read json files properly in a jar.
- Move the list of allowed module keywords in `DataFetcherManager` to a constants class and add the rest of the required modules to it. Modules.json is also updated with all their new info.
- Edit `SearchCommand` so that it displays "None" instead of null when a module doesn't have preclusions/prerequisites.

### PR DESCRIPTION
**Pull request by Silvernitro**
- Move the list of allowed module keywords in `DataFetcherManager` to a constants class and add the rest of the required modules to it. `Modules.json` is also updated with all their new info.
- Minor: Edit `SearchCommand` so that it displays "None" instead of `null` when a module doesn't have preclusions/prerequisites.

**Fix resource dependencies**
Previously, NUSmods used `FileUtil.readJsonFile()` to read data from  `modules.json`. However, this doesn't work when our resource is bundled by ShadowJAR into a jar file. As such, our `search` doesn't work when we run Gradpad offline from the jar release.

Intuitively, you can imagine that there's no such thing as "folders" in a jar file, or at least the structure won't be the same. So we can't just load data from `someDirectory/modules.json` cos that path doesn't make sense in a jar file. Instead, we need to use `classLoaders` to get runtime paths: https://mkyong.com/java/java-read-a-file-from-resources-folder/

I've changed `NusmodsDataManager` to use a method that does this. If you wanna test, build GradPad to a shadowJar and run it without internet. Previously, the `search` command shouldn't work, but now it should since it can load the json file properly.

Since `NusmodsDataManager` has changed, I've also updated its tests and had to move the test data json files from the `test/data` folder to the `test/resources` folder. All tests that use these files have also been updated accordingly.

### CODE REVIEW

File: src/main/java/seedu/address/nusmods/DataFetcher.java [hunk 1]
```diff
@@ -5,7 +5,8 @@
 import seedu.address.nusmods.exceptions.NusmodsException;
 
 public abstract class DataFetcher {
-    public static final String DATA_FILE_PATH = "modules.json";
+    public static final String DATA_FILE_PATH = "data/modules.json";
+    public static final String SAVE_DATA_FILE_PATH = "./src/main/resources/data/modules.json";
```
Comment (Silvernitro) [inline src/main/java/seedu/address/nusmods/DataFetcher.java:9]: We still need this normal file path cos it tells GradPad where to save data to

File: src/test/java/seedu/address/nusmods/DataFetcherManagerTest.java [hunk 2]
```diff
@@ -125,14 +125,17 @@ public void fetchAndSaveModules_successfullySaveModuleInfoToFile()
...
-        Optional<ModuleInfo> expectedModule = JsonUtil.readJsonFile(Paths.get(CS1010X_MODULE_INFO), ModuleInfo.class);
+
+        Optional<ModuleInfo> expectedCs1010x = JsonUtil.readJsonFile(Paths.get(CS1010X_MODULE_INFO), ModuleInfo.class);
+        Optional<ModuleInfo> expectedIs1103 = JsonUtil.readJsonFile(Paths.get(IS1103_MODULE_INFO), ModuleInfo.class);
 
         // clean up test data file after we're done
         Files.deleteIfExists(Paths.get(TEST_SAVE_FILE_PATH));
 
-        if (expectedModule.isPresent()) {
+        if (expectedCs1010x.isPresent() && expectedIs1103.isPresent()) {
```
Comment (Silvernitro) [inline src/test/java/seedu/address/nusmods/DataFetcherManagerTest.java:135]: Updated this and added IS1103 cos its now part of the list of new required modules

**Review by yan-soon — APPROVED** [review]
LGTM! Superb find Sam! 😤💯😫😫💯💯💦💦
